# Generated by Django 3.1.6 on 2021-02-11 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isladeloscuernos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Soltera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ciudad', models.CharField(max_length=100)),
                ('profesion', models.CharField(max_length=100)),
                ('foto', models.CharField(max_length=100)),
                ('edad', models.IntegerField(default=0)),
                ('votos', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Soltero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ciudad', models.CharField(max_length=100)),
                ('profesion', models.CharField(max_length=100)),
                ('foto', models.CharField(max_length=100)),
                ('edad', models.IntegerField(default=0)),
                ('votos', models.IntegerField(default=0)),
            ],
        ),
    ]
